public enum XcodeScripting: String {
    case analyzerissue = "analyzer issue"
    case application = "application"
    case buildconfiguration = "build configuration"
    case builderror = "build error"
    case buildsetting = "build setting"
    case buildwarning = "build warning"
    case device = "device"
    case document = "document"
    case filedocument = "file document"
    case project = "project"
    case resolvedbuildsetting = "resolved build setting"
    case rundestination = "run destination"
    case schemeactionissue = "scheme action issue"
    case schemeactionresult = "scheme action result"
    case scheme = "scheme"
    case sourcedocument = "source document"
    case target = "target"
    case testfailure = "test failure"
    case textdocument = "text document"
    case window = "window"
    case workspacedocument = "workspace document"
}
